apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: 
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 2222
    targetPort: http
  selector:
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: backend
        image: 777953799388.dkr.ecr.ap-northeast-1.amazonaws.com/producer-repo:latest
        ports:
          - name: http
            containerPort: 2222
        env:
          - name: "SVC_NAME"
            value: "backend"
          - name: "SVC_VER"
            value: "1"  
      - name: envoy
        image: 840364872350.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-envoy:v1.12.2.1-prod
        securityContext:
          runAsUser: 1337
        env:
          - name: "APPMESH_VIRTUAL_NODE_NAME"
            value: "mesh/demomesh/virtualNode/backend-vn"
          - name: "ENVOY_LOG_LEVEL"
            value: "info"
          - name: "AWS_REGION"
            value: "ap-northeast-1"
      initContainers:
        - name: proxyinit
          image: 111345817488.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-proxy-route-manager:v2
          securityContext:
            capabilities:
              add: 
                - NET_ADMIN
          env:
            - name: "APPMESH_START_ENABLED"
              value: "1"
            - name: "APPMESH_IGNORE_UID"
              value: "1337"
            - name: "APPMESH_ENVOY_INGRESS_PORT"
              value: "15000"
            - name: "APPMESH_ENVOY_EGRESS_PORT"
              value: "15001"
            - name: "APPMESH_APP_PORTS"
              value: "2222"
            - name: "APPMESH_EGRESS_IGNORED_IP"
              value: "169.254.169.254" 
            
