apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels: 
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  selector:
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: 777953799388.dkr.ecr.ap-northeast-1.amazonaws.com/consumer-repo:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:       
          - name: "serviceName"
            value: "frontend"                  
          - name: "versionNum"
            value: "1.0"                  
          - name: envoy
        image: 111345817488.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-envoy:v1.9.1.0-prod
        securityContext:
          runAsUser: 1337
        env:
          - name: "APPMESH_VIRTUAL_NODE_NAME"
            value: "mesh/apps/virtualNode/frontend-vn"
          - name: "ENVOY_LOG_LEVEL"
            value: "info"
          - name: "AWS_REGION"
            value: "ap-northeast-1"
      initContainers:
        - name: proxyinit
          image: 111345817488.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-proxy-route-manager:v2
          securityContext:
            capabilities:
              add: 
                - NET_ADMIN
          env:
            - name: "APPMESH_START_ENABLED"
              value: "1"
            - name: "APPMESH_IGNORE_UID"
              value: "1337"
            - name: "APPMESH_ENVOY_INGRESS_PORT"
              value: "15000"
            - name: "APPMESH_ENVOY_EGRESS_PORT"
              value: "15001"
            - name: "APPMESH_APP_PORTS"
              value: "8080"
            - name: "APPMESH_EGRESS_IGNORED_IP"
              value: "169.254.169.254"          
---          
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: 
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 2222
    targetPort: http
  selector:
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: backend
        image: 777953799388.dkr.ecr.ap-northeast-1.amazonaws.com/producer-repo:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 2222
        env:       
          - name: "serviceName"
            value: "backend"                  
          - name: "versionNum"
            value: "1.0"                  
          - name: envoy
        image: 111345817488.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-envoy:v1.9.1.0-prod
        securityContext:
          runAsUser: 1337
        env:
          - name: "APPMESH_VIRTUAL_NODE_NAME"
            value: "mesh/apps/virtualNode/backend-vn"
          - name: "ENVOY_LOG_LEVEL"
            value: "info"
          - name: "AWS_REGION"
            value: "ap-northeast-1"
      initContainers:
        - name: proxyinit
          image: 111345817488.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-proxy-route-manager:v2
          securityContext:
            capabilities:
              add: 
                - NET_ADMIN
          env:
            - name: "APPMESH_START_ENABLED"
              value: "1"
            - name: "APPMESH_IGNORE_UID"
              value: "1337"
            - name: "APPMESH_ENVOY_INGRESS_PORT"
              value: "15000"
            - name: "APPMESH_ENVOY_EGRESS_PORT"
              value: "15001"
            - name: "APPMESH_APP_PORTS"
              value: "2222"
            - name: "APPMESH_EGRESS_IGNORED_IP"
              value: "169.254.169.254"          
---   

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels: 
    tier: discovery
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 1111
    targetPort: http
  selector:
    tier: discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: discovery
  template:
    metadata:
      labels:
        tier: discovery
    spec:
      containers:
      - name: eureka
        image: 777953799388.dkr.ecr.ap-northeast-1.amazonaws.com/eks-repo:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 1111
        env:       
        - name: "serviceName"
          value: "eureka"                  
        - name: "versionNum"
          value: "1.0"                  
        - name: envoy
        image: 111345817488.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-envoy:v1.9.1.0-prod
        securityContext:
          runAsUser: 1337
        env:
          - name: "APPMESH_VIRTUAL_NODE_NAME"
            value: "mesh/apps/virtualNode/eureka-vn"
          - name: "ENVOY_LOG_LEVEL"
            value: "info"
          - name: "AWS_REGION"
            value: "ap-northeast-1"
      initContainers:
        - name: proxyinit
          image: 111345817488.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-proxy-route-manager:v2
          securityContext:
            capabilities:
              add: 
                - NET_ADMIN
          env:
            - name: "APPMESH_START_ENABLED"
              value: "1"
            - name: "APPMESH_IGNORE_UID"
              value: "1337"
            - name: "APPMESH_ENVOY_INGRESS_PORT"
              value: "15000"
            - name: "APPMESH_ENVOY_EGRESS_PORT"
              value: "15001"
            - name: "APPMESH_APP_PORTS"
              value: "1111"
            - name: "APPMESH_EGRESS_IGNORED_IP"
              value: "169.254.169.254"  

       
